using System.ComponentModel;

namespace E3Series.Wrapper.Entities.Models
{
    public enum SignalNameType
    {
        [Description("SIgnal name not set")]
        NotSet,
        [Description("System autogenerated signal name")]
        System,
        [Description("Signal name set by user")]
        User
    }
}